### ISSUE TITLE
Odd Duplication glitch in get_places_in

### ISSUE THREAD

**Issue by lukesmurray** [datacommonsorg/api-python#81]
Sometimes `get_places_in` will return duplicate values which are unexpected.

For example, try to get the SchoolDistricts in [Lunenburg County](https://browser.datacommons.org/kg?dcid=geoId/51111&db=). There is only [one school district](https://nces.ed.gov/ccd/districtsearch/district_list.asp?Search=1&details=1&InstName=&DistrictID=&Address=&City=&State=51&Zip=&Miles=&County=Lunenburg+County&PhoneAreaCode=&Phone=&DistrictType=1&DistrictType=2&DistrictType=3&DistrictType=4&DistrictType=5&DistrictType=6&DistrictType=7&DistrictType=8&NumOfStudents=&NumOfStudentsRange=more&NumOfSchools=&NumOfSchoolsRange=more) in Lunenberg County. The school district returned here is correct but it is returned twice.

```python
>>> dc.get_places_in(pd.Series(['geoId/51111']), 'SchoolDistrict').tolist()[0]
['geoId/sch5102310', 'geoId/sch5102310']
```

**Comment by shifucun** [comment]
Fixed in https://github.com/datacommonsorg/mixer/pull/16
