### ISSUE TITLE
[API v1.0.0 Feedback] `Query` should be a function not a class

### ISSUE THREAD

**Issue by ACscooter** [datacommonsorg/api-python#91]
Currently, `sparql` querying capability is implemented as a class. This is largely unnecessary and can be implemented as a function. 

The benefits are

- The R Client API can simply wrap the query function instead of having to implement its own query logic.
- It aligns with other functions in the Python Client API.

See [this PR](https://github.com/datacommonsorg/api-r/pull/1) for more details.

**Comment by shifucun** [comment]
Fixed in https://github.com/datacommonsorg/api-python/pull/94
