### ISSUE TITLE
[API v1.0.0 Feedback] Implement `GetPopObs` and `GetPlaceObs` wrappers.

### ISSUE THREAD

**Issue by ACscooter** [datacommonsorg/api-python#92]
`GetPopObs` and `GetPlaceObs` are implemented in the REST API. These should be wrapped by the Python Client API so that one can easily build a node based browser.

**Comment by shifucun** [comment]
Implemented in https://github.com/datacommonsorg/api-python/pull/93 and https://github.com/datacommonsorg/api-python/pull/94
